# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2bb3409464999d8eba409172cc1821cea5e2db9b503d8324763e9b2e2af27fab44d44f3ed92ba1925ebdbf6b9981a10b16a745ea20bc5ae887404cadbc99987

test:
  secret_key_base: cf7f480d19f4f4342ad43ff31152829bdffa0eecb22022d967dfa113e891881d0024c5fa58817c408162764d98afc5912529924317bdc7df7e8862bd585a6cb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
